function AnalyzeArticle(url)
%% Analyze Japanese Text Data
% https://jp.mathworks.com/help/textanalytics/ug/analyze-japanese-text.html

options = weboptions('CharacterEncoding','UTF-8');
code = webread(url,options);

%% output page

tree = htmlTree(code);
htmltitletext = string(findElement(tree,"title"));
htmltitletext = extractBetween(htmltitletext,'>',' | ');
htmltitletext = replace(htmltitletext,' ','_');
newsdatetime = string(datetime(strtrim(extractBetween(string(findElement(tree,'article')),'<DIV id="news_day">','日')),'InputFormat','yyyy年MM月dd','Format','yyyy-MM-dd'));

if all(size(newsdatetime) == [0 1])
    datepattern = digitsPattern(4)+lettersPattern(1,2)+digitsPattern(1,2)+lettersPattern(1,2)+digitsPattern(1,2);
    newsdatetime = extract(htmltitletext,datepattern);
    newsdatetime = string(datetime(newsdatetime,'InputFormat','yyyy年MM月dd','Format','yyyy-MM-dd'));
end

disp(newsdatetime)
disp(htmltitletext)

if all(size(newsdatetime) == [0 1])
    disp("Failed detection date. Allocate page generated date.")
    newsdatetime = string(datetime('now','Format','yyyy-MM-dd'));
end

pagefilename = newsdatetime + '-' + htmltitletext + '.md';
imagehash = hashcalc(htmltitletext);
imagefilename = imagehash + '.png';

if htmltitletext == ""
    disp("↑Cannot find title. Skip......")
    return;
end

if isfile(sprintf('./docs/assets/%s',imagefilename))
    disp("↑Exist. Skip......")
    return;
end


%% Text Analysis
% Extract the text data from the HTML using |extractHTMLText|. Split the text 
% by |newline| characters.

textData = extractHTMLText(code);
textData = string(split(textData,newline));

idx_emptyline = textData == "";
textData(idx_emptyline) = [];

%% Word Cloud
% Visualize the text data in a word cloud.

fig = figure;
wordcloud(textData);

saveas(fig,"./docs/assets/" + imagefilename)
close;

%% Output Pages

frontmatter = ["---" + newline +...
"layout: post"+ newline +...
"title: " + htmltitletext + newline +...
"---"];

pagecontent = [frontmatter + newline +...
    "Autogenerated Word Cloud."+ newline +...
    "Source\: [" + url + "](" + url + ")" + newline +...
    "![WordCloud](" + "{{ site.baseurl }}/assets/" + imagefilename + ")"];

fileID = fopen("./docs/_posts/" + pagefilename,'w');
fprintf(fileID,'%s',pagecontent);
fclose(fileID);


%% Hash calculation function
function out = hashcalc(in)
%https://jp.mathworks.com/matlabcentral/answers/45323-how-to-calculate-hash-sum-of-a-string-using-java
% Import HASH calculation package
import java.security.*;
import java.math.*;
testname = char(strjoin(string(uint32(char(in))),''));

md = MessageDigest.getInstance('MD5');
hash = md.digest(double(testname));
bi = BigInteger(1, hash);
out = string(bi.toString(16));
end
end